# Generated by Django 3.1.2 on 2021-01-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=100, verbose_name='ユーザーID')),
                ('lending_day', models.DateTimeField()),
                ('return_day', models.DateTimeField()),
                ('returned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Camera_manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100, verbose_name='カメラ名')),
                ('camera_quantity', models.IntegerField(null=True)),
                ('camera_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='備品名')),
                ('equipment_quantity', models.IntegerField(null=True)),
                ('equipment_number', models.IntegerField()),
            ],
        ),
    ]
