# Generated by Django 3.1.2 on 2020-11-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lending_day', models.DateTimeField(auto_now=True)),
                ('return_day', models.DateTimeField(auto_now=True)),
                ('not_returned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=200)),
                ('gender', models.BooleanField()),
                ('grade', models.IntegerField()),
                ('course', models.CharField(max_length=10)),
            ],
        ),
    ]
