# Generated by Django 3.1.2 on 2020-11-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera_manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('camera_number', models.IntegerField()),
                ('equipment', models.CharField(max_length=100)),
                ('equipment_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
