# Generated by Django 3.1.2 on 2021-01-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku_system', '0002_auto_20210123_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='camera_name',
            field=models.CharField(default='', max_length=100, verbose_name='カメラ名'),
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment_name',
            field=models.CharField(default='', max_length=100, verbose_name='備品名'),
        ),
    ]
