# Generated by Django 3.1.2 on 2021-01-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku_system', '0003_auto_20210123_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_ID',
            new_name='user_name',
        ),
    ]
