# Generated by Django 3.1.2 on 2020-11-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku_system', '0003_auto_20201116_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='camera_manage',
            name='camera_name',
            field=models.CharField(max_length=100, verbose_name='カメラ名'),
        ),
        migrations.AlterField(
            model_name='equipment_manage',
            name='equipment_name',
            field=models.CharField(max_length=100, verbose_name='備品名'),
        ),
    ]
