# Generated by Django 3.1.2 on 2020-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku_system', '0004_auto_20201117_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera_manage',
            name='camera_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipment_manage',
            name='equipment_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
