# Generated by Django 3.1.2 on 2021-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku_system', '0004_auto_20210123_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_ID',
            field=models.CharField(default='', max_length=100, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='', max_length=100, verbose_name='ユーザー名'),
        ),
    ]
