# Generated by Django 3.1.2 on 2020-12-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoyaku_system', '0005_auto_20201121_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='not_returned',
            new_name='returned',
        ),
    ]
